---
title: "Initial Replication attempts"
author: "Evelyn Cai"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load necessary libraries
library(tidyverse)
library(utils)
library(ggmosaic)
library(ggplot2)
library(cregg)
library(corrplot)
library(gridExtra)

# Decompress the file (Commented out because already completed once)
# untar(tarfile = "ReplicationPackage (1).tar.gz")

# Read in .csv files as dataframes
DD_lo <- read_csv("ReplicationPackage/data/actual-lower-2014-allcandidates.csv")
DD_up <- read_csv("ReplicationPackage/data/actual-upper-2013-allcandidates.csv")
```

```{r, AMCE_plots_WORKING}

load("ReplicationPackage/output/conjoint.RData")

# Rename the volumns with multiple strings for names, which confuses cj()

DD <- DD %>%
  rename("Education" = `Highest Educational Attainment`,
         "Previous_Occupation" = `Prior Occupation`,
         "Parent_Political_Background" = `Parental Political Background`)

DD_cj <- cj(DD, formula = Y.1 ~ Party + Age + Experience + Hometown + Education + Previous_Occupation, estimate = "amce", by = ~Gender)

DD_diff <- cj(DD, formula = Y.1 ~ Party + Age + Experience + Hometown + Education + Previous_Occupation, estimate = "amce_diff", by = ~Gender)

plot(rbind(DD_cj, DD_diff)) + ggplot2::facet_wrap(~BY, ncol = 3L) + ggplot2::labs(title = "AMCE by Gender", caption = "Data from Horiuchi, Smith, & Yamamato via Dataverse") + ggthemes::theme_few()

```

```{r pre_processing_data}
### Recoding Variables

## System type indicators

# Create a new column called win_type_1 that encodes the results from the
#DD_lo$result column.

DD_lo <- DD_lo %>%
  mutate(win_type_1 = as.factor(case_when(result == 1 ~ "SMD",
                                result == 2 ~"Zombie",
                                result == 3 ~ "PR",
                                TRUE ~ NA_character_)),
         elec_type_1 = case_when(prcode == 0 ~ "SMD",
                                 kucode == 0 ~ "PR",
                                 TRUE ~ "Both"),
         elec_type_2 = as.character(case_when(elec_type_1 == "SMD" | elec_type_1 == "Both" ~ "SMD/Dual",
                                 TRUE ~ elec_type_1)))


DD_up <- DD_up %>%
  mutate(win_type_1 = as.factor(districttype),
         elec_type_1 = win_type_1,
         win_type_2 = case_when(win_type_1 == "SMD" | win_type_1 == "MMD" ~ "SNTV",
                                win_type_1 == "PR" ~ "PR",
                                TRUE ~ NA_character_),
         elec_type_2 = as.character(win_type_2))

# Recode values

DDD <- list(DD_lo, DD_up)

for(i in 1:length(DDD))
  {DD <- DDD[[i]] %>%
    mutate(win = case_when(result > 0 ~ 1,
                           TRUE ~ 0),
           celeb = as.factor(case_when(celeb == 0 ~ "No",
                                       celeb == 1 ~ "Yes",
                                       TRUE ~ NA_character_)),
           busi_emp = as.factor(case_when(busi_emp == 0 ~ "No",
                                          busi_emp == 1 ~ "Yes",
                                          TRUE ~ NA_character_)),
           busi_exec = as.factor(case_when(busi_exec == 0 ~ "No",
                                           busi_exec == 1 ~ "Yes",
                                           TRUE ~ NA_character_)),
           bcrat = as.factor(case_when(bcrat == 0 ~ "No",
                                       bcrat == 1 ~ "Yes",
                                       TRUE ~ NA_character_)),
           localbcrat = as.factor(case_when(localbcrat == 0 ~ "No",
                                            localbcrat == 1 ~ "Yes",
                                            TRUE ~ NA_character_)),
           pref_assy = as.factor(case_when(pref_assy == 0 ~ "No",
                                           pref_assy == 1 ~ "Yes",
                                           TRUE ~ NA_character_)),
           sec = as.factor(case_when(sec == 0 ~ "No",
                                     sec == 1 ~ "Yes",
                                     TRUE ~ NA_character_)),
           experience_lab = as.character(experience_lab),
           experience_lab = factor(experience_lab, levels = c("Currently in office, 3+ terms", "Currently in office, 2 terms", "Currently in office, 1 term", "Formerly in office, 3+ terms", "Formerly in office, 2 terms", "Formerly in office, 1 term", "No experience")),
           age_lab = as.character(case_when(age < 40 ~ "Under 40",
                                         age >= 40 & age < 50 ~ "40 - 49",
                                         age >= 50 & age < 60 ~ "50 - 59",
                                         age >= 60 & age < 70 ~ "60 - 69",
                                         age >= 70 ~ "70 or over",
                                         TRUE ~ NA_character_)),
           age_lab = factor(age_lab, levels = c("Under 40", "40 - 49", "50 - 59", "60 - 69", "70 or over")),
           educ_lab = as.character(educ_lab),
           educ_lab = as.factor(case_when(educ_lab == "Local public university" ~ "Other public university",
                                          TRUE ~ educ_lab)),
           party_en = factor(party_en, levels = c("LDP", "Komeito", "JCP", "DPJ")),
           home_lab = factor(home_lab, ordered = TRUE),
           dynastic_lab = as_factor(case_when(dynastic_lab == "Local-level elected politician" ~ "Loc. Pol.",
                                              dynastic_lab == "National-level elected politician" ~ "MP",
                                              dynastic_lab == "Cabinet minister" ~ "Cab. Min.",
                                              TRUE ~ "None")))
           DDD[[i]] <- DD
}

# Unlist

DD_lo <- DDD[[1]]
DD_up <- DDD[[2]]

# Reorder Levels

# lower house
DD_lo <- DD_lo %>%
  mutate(party_en = factor(party_en, levels = c("Independent","Other","PFG","JIP","LDP","Komeito","DPJ","PLP","SDP","JCP")),
         elec_type_2 = factor(elec_type_2, levels = c("SMD/Dual", "PR")),
         win_type_1 = factor(win_type_1, levels = c("SMD", "Zombie", "PR")))

# upper house
DD_up <- DD_up %>%
  mutate(party_en = factor(party_en, levels = c("Independent","Other","JIP","LDP","Komeito","DPJ","PLP","SDP","JCP")),
         elec_type_2 = factor(elec_type_2, levels = c("SMD", "SNTV", "PR")))

## Filter for winners

DD_lo_win <- DD_lo %>%
  filter(win == 1)

DD_up_win <- DD_up %>%
  filter(win == 1)
```

``` {r mosaic plot}

load("ReplicationPackage/output/actual.RData")

# Load functions
source("ReplicationPackage/funs/mosprep.R")
source("ReplicationPackage/funs/mospl.R")
source("ReplicationPackage/funs/mospl2.R")

set.seed(2389)

## gender (Fig A.1.a)
DD_lo$by <- DD_lo$gender_lab
DD_up$by <- DD_up$gender_lab
DD_lo_win$by <- DD_lo_win$gender_lab
DD_up_win$by <- DD_up_win$gender_lab

DD_lo_mosaic <- DD_lo %>%
  select(elec_type_2, by) %>%
  group_by(elec_type_2, by) %>%
  count()

# Mosaic plots by gender
gender_DD_lo <- ggplot(DD_lo) + 
  geom_mosaic(aes(x = product(elec_type_2), fill = by)) +
  theme_classic() +
  labs(title = "HR Candidates") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.box.margin = margin(),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_blank())

gender_DD_up <- ggplot(DD_up) + 
  geom_mosaic(aes(x = product(elec_type_2), fill = by)) +
  theme_classic()+
  labs(title = "HC Candidates") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.box.margin = margin(),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_blank())

gender_DD_lo_win <- ggplot(DD_lo_win) + 
  geom_mosaic(aes(x = product(win_type_1), fill = by)) +
  theme_classic() +
  labs(title = "HR Winners") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.box.margin = margin(),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_blank())

gender_DD_up_win <- ggplot(DD_up_win) + 
  geom_mosaic(aes(x = product(elec_type_2), fill = by)) +
  theme_classic() +
  labs(title = "HC Winners") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.box.margin = margin(),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_blank())

gender_DD_lo
gender_DD_up
gender_DD_lo_win
gender_DD_up_win


# Mosaic plots by age
age_DD_lo <- ggplot(DD_lo) + 
  geom_mosaic(aes(x = product(elec_type_2), fill = age_lab)) +
  theme_classic() +
  labs(title = "HR Candidates") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.box.margin = margin(),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_blank())

age_DD_up <- DD_up %>%
  mutate(elec_type_2 = factor(elec_type_2, levels = c("SNTV", "PR"))) %>%
  ggplot() + 
  geom_mosaic(aes(x = product(elec_type_2), fill = age_lab)) +
  theme_classic()+
  labs(title = "HC Candidates") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.box.margin = margin(),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_blank())

age_DD_lo_win <- ggplot(DD_lo_win) + 
  geom_mosaic(aes(x = product(win_type_1), fill = age_lab)) +
  theme_classic() +
  labs(title = "HR Winners") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.box.margin = margin(),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_blank())

age_DD_up_win <- DD_up_win %>%
  mutate(elec_type_2 = factor(elec_type_2, levels = c("SNTV", "PR"))) %>%
  ggplot() +
  geom_mosaic(aes(x = product(elec_type_2), fill = age_lab)) +
  theme_classic() +
  labs(title = "HC Winners") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25),
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_blank(),
        legend.box.margin = margin(),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_blank())

age_DD_lo
age_DD_up
age_DD_lo_win
age_DD_up_win

```

```{r conjoint_plots, echo = FALSE}

# Load conjoint data

# load("ReplicationPackage/output/conjoint.RData")
# 
# # Load functions
# 
# source("ReplicationPackage/funs/plot.amce.mod.R")
# source("ReplicationPackage/funs/plot.amce.difference.R")
# source("ReplicationPackage/funs/theme.nolab.R")
# 
# # Analysis
# 
# # Create new column called ww via function called reweight
# 
# reweight <- TRUE
# 
# if (reweight){
#   DD$ww <- DD$wgt
# } else {
#   DD$ww <- rep(1, nrow(DD))
# }
# 
# # Factorize ideo, urban
# 
# DD <- DD %>%
#   mutate(ideo = as.factor(ideo),
#          urban = as.factor(urban),
#          `Highest Educational Attainment` = case_when(`Highest Educational Attainment` == "High school" ~ "High School",
#                                                        TRUE ~ "University"),
# 
# # Filter for certain variables; include urban
# 
# 
# amce.subset.a <- function(formula, condition = rep(TRUE, nrow(DD)), attribute = NULL, bline){
#   fmla <- update(formula, as.formula(paste0(". ~ . - ", attribute)))
#   ind.baseline <- -match(attribute, names(bline))
#   if(is.na(ind.baseline)) ind.baseline <- 1:length(bline)
#   amce(fmla,
#        data = DD, subset = condition,
#        respondent.id = "id", cluster = TRUE, weights = "ww",
#        baselines=bline[ind.baseline])
# }
# 
# # education x other attributes
# fmla <- Y.1 ~ Party + Age + Gender + Experience + Hometown + `Prior Occupation` + `Parental Political Background`
# out.hs <- amce.subset.a(fmla, DD$`Highest Educational Attainment` == "High School", "Education", baseline)
# out.uni <- amce.subset.a(fmla, DD$`Highest Educational Attainment` == "University", "Education", baseline)
# 
# 
# ### Ploting results
# 
# clevel = .95
# 
# if(reweight){
#   rw <- "rw-"
# } else {
#   rw <- NULL
# }

# Fig on interaction effects

# plot.amce.difference(out.hs, out.uni, "High School", "University")

```


```{r corrplot, warning = FALSE}
# Make correlation matrix (Code mainly unaltered from replication file)

DDD <- list(DD_lo, DD_lo_win, DD_up, DD_up_win)
cormats <- as.list(rep(NA,4))

for(i in 1:length(DDD)){
  DDD[[i]]$experience_bin <- DDD[[i]]$experience > 0
  DDD[[i]]$college <- DDD[[i]]$educ_lab != "High school"
  DDD[[i]]$todai <- DDD[[i]]$educ_lab == "University of Tokyo"
  DDD[[i]]$home_bin <- DDD[[i]]$home_lab == "Born inside district"
  DDD[[i]]$dynastic_bin <- DDD[[i]]$dynastic_lab != "None"
  DDD[[i]]$LDP <- DDD[[i]]$party_en == "LDP"
  DDD[[i]]$DPJ <- DDD[[i]]$party_en == "DPJ"
  DDD[[i]]$JCP <- DDD[[i]]$party_en == "JCP"
  DDD[[i]]$locpol <- DDD[[i]]$pref_assy == "Yes" | DDD[[i]]$pref_gov
  atts <- subset(DDD[[i]], select = c("age", "experience_bin", "female", "college", "todai", "home_bin", "dynastic_bin", "LDP", "DPJ", "JCP", "locpol"))
  names(atts) <- c("Age", "Exp.", "Gender", "Any\n College", "U of\n Tokyo", "Local", "Dynastic", "LDP", "DPJ", "JCP", "Loc. Pol.\n Exp.")
  cormats[[i]] <- cor(atts, use="pairwise")
}

titles <- c("HR Candidates", "HR Winners", "HC Candidates", "HC Winners")

for(i in 1:length(cormats)){
  cormats[[i]][4:5,4:5] <- NA
  cormats[[i]][8:10,8:10] <- NA
}

par(mfrow = c(1,2))
for(i in c(2,4)){
  suppressWarnings(corrplot(cormats[[i]], method = "color", type = "lower", tl.pos = "ld", cl.pos = "n", tl.col = "black", addCoef.col = "black",
                            diag = FALSE, title = titles[i], mar = c(0.1,0.1,1,0.1), na.label = " ", line = -1))
}

```



